/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginAndSignup;

import com.mycompany.portal.DBconnection;
import com.mycompany.portal.Mainpage;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */

    
public class Login extends javax.swing.JFrame {
    
    Connection ConnectDB;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form Login
     */
    public Login() {
           
        initComponents();
        ConnectDB = DBconnection.Conn();
    }
    String LoginStudentID;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
   public void Login(){
       try{ 
             String passDb = null;
        String StudentID = StudentNumberField.getText();
        String UserPass = String.valueOf(PasswordField.getPassword());
          LoginStudentID = StudentID;
            
             st = ConnectDB.createStatement();
            
            String query = "SELECT * FROM LoginInfo WHERE StudentID= '"+StudentID+"'";
            String query2 = "UPDATE recentlogininfo SET recentID ='"+StudentID+"' WHERE ID = 1";
            ResultSet rs = st.executeQuery(query);
            int Found = 0;
            while(rs.next()){
                passDb = rs.getString("User_Password");
                Found = 1;
            }
            if(Found == 1 && UserPass.equals(passDb)){
                this.dispose();
                Thread.sleep(1000) ;
                Mainpage welcomepage = new Mainpage();
                welcomepage.setVisible(true);
                st.executeUpdate(query2);
            }else{
                StudentNumberField.setText("");
                PasswordField.setText("");
            }
            
      }
      catch(HeadlessException | SQLException e){
          System.out.print(e);
      } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundOnly7 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        curvedPanel1 = new topglobalnakaw.CurvedPanel();
        StudentNumberField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        curvedPanel2 = new topglobalnakaw.CurvedPanel();
        Loginbtn = new javax.swing.JLabel();
        curvedPanel3 = new topglobalnakaw.CurvedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BackgroundOnly9 = new javax.swing.JLabel();
        BackgroundOnly2 = new javax.swing.JLabel();
        BackgroundOnly3 = new javax.swing.JLabel();
        BackgroundOnly4 = new javax.swing.JLabel();
        BackgroundOnly5 = new javax.swing.JLabel();
        BackgroundOnly6 = new javax.swing.JLabel();
        BackgroundOnly10 = new javax.swing.JLabel();
        BackgroundOnly11 = new javax.swing.JLabel();
        BackgroundOnly12 = new javax.swing.JLabel();
        BackgroundOnly8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackgroundOnly13 = new javax.swing.JLabel();
        BackgroundOnly14 = new javax.swing.JLabel();
        BackgroundOnly15 = new javax.swing.JLabel();

        BackgroundOnly7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setBackground(new java.awt.Color(255, 255, 204));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        curvedPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        curvedPanel1.setRoundTopRight(25);

        StudentNumberField.setBackground(new java.awt.Color(10, 9, 9));
        StudentNumberField.setForeground(new java.awt.Color(255, 255, 255));
        StudentNumberField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(255, 255, 255)));
        StudentNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentNumberFieldKeyPressed(evt);
            }
        });

        PasswordField.setBackground(new java.awt.Color(10, 9, 9));
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(255, 255, 255)));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });

        curvedPanel2.setBackground(new java.awt.Color(187, 226, 246));

        Loginbtn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(0, 0, 0));
        Loginbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginbtn.setText("Login");
        Loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout curvedPanel2Layout = new javax.swing.GroupLayout(curvedPanel2);
        curvedPanel2.setLayout(curvedPanel2Layout);
        curvedPanel2Layout.setHorizontalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        curvedPanel2Layout.setVerticalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        curvedPanel3.setBackground(new java.awt.Color(187, 226, 246));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign Up");

        javax.swing.GroupLayout curvedPanel3Layout = new javax.swing.GroupLayout(curvedPanel3);
        curvedPanel3.setLayout(curvedPanel3Layout);
        curvedPanel3Layout.setHorizontalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        curvedPanel3Layout.setVerticalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        BackgroundOnly9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N

        javax.swing.GroupLayout curvedPanel1Layout = new javax.swing.GroupLayout(curvedPanel1);
        curvedPanel1.setLayout(curvedPanel1Layout);
        curvedPanel1Layout.setHorizontalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, curvedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(curvedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curvedPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField)
                    .addComponent(StudentNumberField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundOnly9)
                .addContainerGap())
        );
        curvedPanel1Layout.setVerticalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackgroundOnly9)
                    .addGroup(curvedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(curvedPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addGroup(curvedPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(curvedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(curvedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Login.add(curvedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 410, 380));

        BackgroundOnly2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, -1, 130));

        BackgroundOnly3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 510, -1));

        BackgroundOnly4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 510, 120));

        BackgroundOnly5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, -1));

        BackgroundOnly6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        BackgroundOnly10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 120, -1));

        BackgroundOnly11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 130));

        BackgroundOnly12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        BackgroundOnly8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 120));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        Login.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 138));

        BackgroundOnly13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        BackgroundOnly14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, -1, -1));

        BackgroundOnly15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        Login.add(BackgroundOnly15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked
        Login();
    }//GEN-LAST:event_LoginbtnMouseClicked

    private void StudentNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentNumberFieldKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            Login();
        }
    }//GEN-LAST:event_StudentNumberFieldKeyPressed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            Login();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundOnly10;
    private javax.swing.JLabel BackgroundOnly11;
    private javax.swing.JLabel BackgroundOnly12;
    private javax.swing.JLabel BackgroundOnly13;
    private javax.swing.JLabel BackgroundOnly14;
    private javax.swing.JLabel BackgroundOnly15;
    private javax.swing.JLabel BackgroundOnly2;
    private javax.swing.JLabel BackgroundOnly3;
    private javax.swing.JLabel BackgroundOnly4;
    private javax.swing.JLabel BackgroundOnly5;
    private javax.swing.JLabel BackgroundOnly6;
    private javax.swing.JLabel BackgroundOnly7;
    private javax.swing.JLabel BackgroundOnly8;
    private javax.swing.JLabel BackgroundOnly9;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Loginbtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField StudentNumberField;
    private topglobalnakaw.CurvedPanel curvedPanel1;
    private topglobalnakaw.CurvedPanel curvedPanel2;
    private topglobalnakaw.CurvedPanel curvedPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  
}

