/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.portal;

import LoginAndSignup.Login;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author admin
 */
public class Classinformation extends javax.swing.JInternalFrame {
    
 
    

    /**
     * Creates new form Classinformation
     */
    public Classinformation() {
        initComponents();
        
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI panel = (BasicInternalFrameUI) this.getUI();
        panel.setNorthPane(null);    
    }
    
  public void LoadData(){
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String path = "C:\\Users\\admin\\Documents\\NetBeansProjects\\Portal\\db\\DatabaseNiBFF.accdb";
            String url = "jdbc:ucanaccess://" + path;  
            Connection connect = DriverManager.getConnection(url);
            Statement st = connect.createStatement();
            String StudentID = null;
            String query = "SELECT recentID FROM recentlogininfo WHERE ID= 1";
            ResultSet rs = st.executeQuery(query);
  
            while(rs.next()){
                StudentID = rs.getString(1);               
            }
            String query2 = "SELECT * FROM Main_Profile_ICT_12B WHERE Student_Number='"+StudentID+"'";
            ResultSet rs2 = st.executeQuery(query2);
            System.out.println(rs2);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        curvedPanel1 = new topglobalnakaw.CurvedPanel();
        curvedPanel2 = new topglobalnakaw.CurvedPanel();
        maricar = new javax.swing.JLabel();
        bryan = new javax.swing.JLabel();
        gill = new javax.swing.JLabel();
        precious = new javax.swing.JLabel();
        lance = new javax.swing.JLabel();
        nicole = new javax.swing.JLabel();
        mark = new javax.swing.JLabel();
        curvedPanel3 = new topglobalnakaw.CurvedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        curvedPanel4 = new topglobalnakaw.CurvedPanel();
        curvedPanel5 = new topglobalnakaw.CurvedPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BackgroundOnly7 = new javax.swing.JLabel();
        BackgroundOnly1 = new javax.swing.JLabel();
        BackgroundOnly2 = new javax.swing.JLabel();
        BackgroundOnly11 = new javax.swing.JLabel();
        BackgroundOnly6 = new javax.swing.JLabel();
        BackgroundOnly3 = new javax.swing.JLabel();
        BackgroundOnly4 = new javax.swing.JLabel();
        BackgroundOnly8 = new javax.swing.JLabel();
        BackgroundOnly12 = new javax.swing.JLabel();
        BackgroundOnly5 = new javax.swing.JLabel();
        BackgroundOnly15 = new javax.swing.JLabel();
        BackgroundOnly10 = new javax.swing.JLabel();
        BackgroundOnly16 = new javax.swing.JLabel();
        BackgroundOnly9 = new javax.swing.JLabel();
        BackgroundOnly13 = new javax.swing.JLabel();
        BackgroundOnly14 = new javax.swing.JLabel();
        BackgroundOnly17 = new javax.swing.JLabel();
        BackgroundOnly18 = new javax.swing.JLabel();
        BackgroundOnly19 = new javax.swing.JLabel();
        BackgroundOnly20 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 232, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Class Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, 300, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ICT 12 - D Class Schedule");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 430, 33));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("[ CLASS ADVISER ]");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 300, 320, 80));

        curvedPanel1.setBackground(new java.awt.Color(222, 212, 208));

        curvedPanel2.setBackground(new java.awt.Color(243, 242, 237));

        maricar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        maricar.setForeground(new java.awt.Color(0, 0, 0));
        maricar.setText(" EAPP - MMD @Ccst Maricar Dela Peña");
        maricar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maricar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maricar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maricarMouseClicked(evt);
            }
        });

        bryan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bryan.setForeground(new java.awt.Color(0, 0, 0));
        bryan.setText(" ENTREP - BY @Ccst Bryan Yaquiten");
        bryan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bryan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bryan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bryanMouseClicked(evt);
            }
        });

        gill.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gill.setForeground(new java.awt.Color(0, 0, 0));
        gill.setText(" P.E - JGR @Ccst John Gill Rueda");
        gill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gillMouseClicked(evt);
            }
        });

        precious.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        precious.setForeground(new java.awt.Color(0, 0, 0));
        precious.setText(" IMMERSION - PHM @Ccst Precious Maningas");
        precious.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        precious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        precious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preciousMouseClicked(evt);
            }
        });

        lance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lance.setForeground(new java.awt.Color(0, 0, 0));
        lance.setText(" III - LTA @Ccst Lance Austria");
        lance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanceMouseClicked(evt);
            }
        });

        nicole.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nicole.setForeground(new java.awt.Color(0, 0, 0));
        nicole.setText(" CA - NVE @Ccst Nicole Anne Esguearra");
        nicole.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nicole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nicole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nicoleMouseClicked(evt);
            }
        });

        mark.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mark.setForeground(new java.awt.Color(0, 0, 0));
        mark.setText(" ICT - MLV @Ccst Mark Verzon");
        mark.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout curvedPanel2Layout = new javax.swing.GroupLayout(curvedPanel2);
        curvedPanel2.setLayout(curvedPanel2Layout);
        curvedPanel2Layout.setHorizontalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maricar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nicole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bryan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precious, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
        curvedPanel2Layout.setVerticalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maricar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicole, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bryan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gill, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precious, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout curvedPanel1Layout = new javax.swing.GroupLayout(curvedPanel1);
        curvedPanel1.setLayout(curvedPanel1Layout);
        curvedPanel1Layout.setHorizontalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel1Layout.createSequentialGroup()
                .addComponent(curvedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        curvedPanel1Layout.setVerticalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(curvedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(curvedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 470, 540));

        curvedPanel3.setBackground(new java.awt.Color(222, 212, 208));

        jTextArea1.setBackground(new java.awt.Color(243, 242, 237));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("   11:30 - 1:30               11:00 - 1:30              11:30 - 1:30\n           III                             ICT                      ENTREP\n          405                            CL3                          405\n\n\n    1:30 - 3:00                  2:00 - 3:30               1:00 - 2:00\n        EAPP                           CA                          P.E\n         405                             405                          405\n\n\n                                                                     2:00 - 3:00\n                                                                  IMMERSION\n                                                                           405 ");
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBackground(new java.awt.Color(243, 242, 237));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("    TUESDAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(243, 242, 237));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("         FRIDAY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(243, 242, 237));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("    WEDNESDAY");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout curvedPanel3Layout = new javax.swing.GroupLayout(curvedPanel3);
        curvedPanel3.setLayout(curvedPanel3Layout);
        curvedPanel3Layout.setHorizontalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(curvedPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        curvedPanel3Layout.setVerticalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, curvedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(curvedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 510, 410));

        curvedPanel4.setBackground(new java.awt.Color(222, 212, 208));

        curvedPanel5.setBackground(new java.awt.Color(243, 242, 237));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("[ ADVISER NAME ]");

        javax.swing.GroupLayout curvedPanel5Layout = new javax.swing.GroupLayout(curvedPanel5);
        curvedPanel5.setLayout(curvedPanel5Layout);
        curvedPanel5Layout.setHorizontalGroup(
            curvedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        curvedPanel5Layout.setVerticalGroup(
            curvedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout curvedPanel4Layout = new javax.swing.GroupLayout(curvedPanel4);
        curvedPanel4.setLayout(curvedPanel4Layout);
        curvedPanel4Layout.setHorizontalGroup(
            curvedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(curvedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        curvedPanel4Layout.setVerticalGroup(
            curvedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, curvedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(curvedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(curvedPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 390, 260, 80));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Subject Teachers");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 91, 370, 33));

        BackgroundOnly7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, -1, -1));

        BackgroundOnly1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundOnly2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        BackgroundOnly11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, -1, -1));

        BackgroundOnly6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        BackgroundOnly3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        BackgroundOnly4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 240, -1));

        BackgroundOnly8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 250, 240, -1));

        BackgroundOnly12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 500, 240, -1));

        BackgroundOnly5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        BackgroundOnly15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 750, -1, 60));

        BackgroundOnly10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        BackgroundOnly16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 750, 240, 60));

        BackgroundOnly9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        BackgroundOnly13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 810, 230, 60));

        BackgroundOnly14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 750, -1, 60));

        BackgroundOnly17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, 60));

        BackgroundOnly18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, -1, 60));

        BackgroundOnly19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 810, -1, 60));

        BackgroundOnly20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        jPanel1.add(BackgroundOnly20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 810, -1, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lanceMouseClicked

    private void markMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_markMouseClicked

    private void nicoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicoleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nicoleMouseClicked

    private void maricarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maricarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maricarMouseClicked

    private void bryanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bryanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bryanMouseClicked

    private void gillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gillMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gillMouseClicked

    private void preciousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preciousMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_preciousMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundOnly1;
    private javax.swing.JLabel BackgroundOnly10;
    private javax.swing.JLabel BackgroundOnly11;
    private javax.swing.JLabel BackgroundOnly12;
    private javax.swing.JLabel BackgroundOnly13;
    private javax.swing.JLabel BackgroundOnly14;
    private javax.swing.JLabel BackgroundOnly15;
    private javax.swing.JLabel BackgroundOnly16;
    private javax.swing.JLabel BackgroundOnly17;
    private javax.swing.JLabel BackgroundOnly18;
    private javax.swing.JLabel BackgroundOnly19;
    private javax.swing.JLabel BackgroundOnly2;
    private javax.swing.JLabel BackgroundOnly20;
    private javax.swing.JLabel BackgroundOnly3;
    private javax.swing.JLabel BackgroundOnly4;
    private javax.swing.JLabel BackgroundOnly5;
    private javax.swing.JLabel BackgroundOnly6;
    private javax.swing.JLabel BackgroundOnly7;
    private javax.swing.JLabel BackgroundOnly8;
    private javax.swing.JLabel BackgroundOnly9;
    private javax.swing.JLabel bryan;
    private topglobalnakaw.CurvedPanel curvedPanel1;
    private topglobalnakaw.CurvedPanel curvedPanel2;
    private topglobalnakaw.CurvedPanel curvedPanel3;
    private topglobalnakaw.CurvedPanel curvedPanel4;
    private topglobalnakaw.CurvedPanel curvedPanel5;
    private javax.swing.JLabel gill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lance;
    private javax.swing.JLabel maricar;
    private javax.swing.JLabel mark;
    private javax.swing.JLabel nicole;
    private javax.swing.JLabel precious;
    // End of variables declaration//GEN-END:variables
}
