/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.portal;

import static com.mycompany.portal.ReportCard.jLabel13;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author admin
 */
public class MainProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainProfile
     */
    public MainProfile() {
        try {
            File importTitleFont = new File("src/main/resources/BebasNeue-Regular.ttf");
            
//            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont).deriveFont(60f);
            
            StudentName.setFont(Font.createFont(Font.TRUETYPE_FONT, importTitleFont).deriveFont(35f));
        } catch (Exception e) {
        }
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI panel = (BasicInternalFrameUI) this.getUI();
        panel.setNorthPane(null);   
        
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        curvedPanel1 = new LoginAndSignup.CurvedPanel();
        curvedPanel2 = new LoginAndSignup.CurvedPanel();
        StudentName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StudentNumber = new javax.swing.JLabel();
        RatingText = new javax.swing.JLabel();
        GradeLevelText2 = new javax.swing.JLabel();
        GradeAndSectionText = new javax.swing.JLabel();
        RegularStudentText = new javax.swing.JLabel();
        StrandText1 = new javax.swing.JLabel();
        curvedPanel3 = new LoginAndSignup.CurvedPanel();
        curvedPanel4 = new LoginAndSignup.CurvedPanel();
        jSeparator2 = new javax.swing.JSeparator();
        MobileNumberTextHolder = new javax.swing.JLabel();
        GuardianMobileNumberActual = new javax.swing.JLabel();
        EmailTextHolder = new javax.swing.JLabel();
        GuardianEmailActual = new javax.swing.JLabel();
        GuardianFacebookAccountTextHolder = new javax.swing.JLabel();
        GuardianFbAccountActual = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        GuardianMobileNumberTextHolder = new javax.swing.JLabel();
        FacebookAccountTextHolder1 = new javax.swing.JLabel();
        StudentMobileNumberActual1 = new javax.swing.JLabel();
        StudentFbAccountActual1 = new javax.swing.JLabel();
        EmailTextHolder1 = new javax.swing.JLabel();
        EmailActual1 = new javax.swing.JLabel();
        GuardianNameTextHolder = new javax.swing.JLabel();
        GuardianNameActual = new javax.swing.JLabel();
        curvedPanel5 = new LoginAndSignup.CurvedPanel();
        curvedPanel6 = new LoginAndSignup.CurvedPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        StudentFormerSectionsActual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BackgroundOnly6 = new javax.swing.JLabel();
        BackgroundOnly5 = new javax.swing.JLabel();
        BackgroundOnly2 = new javax.swing.JLabel();
        BackgroundOnly3 = new javax.swing.JLabel();
        BackgroundOnly1 = new javax.swing.JLabel();
        BackgroundOnly9 = new javax.swing.JLabel();
        BackgroundOnly4 = new javax.swing.JLabel();
        BackgroundOnly7 = new javax.swing.JLabel();
        BackgroundOnly8 = new javax.swing.JLabel();
        BackgroundOnly10 = new javax.swing.JLabel();
        BackgroundOnly11 = new javax.swing.JLabel();
        BackgroundOnly12 = new javax.swing.JLabel();
        BackgroundOnly13 = new javax.swing.JLabel();
        BackgroundOnly14 = new javax.swing.JLabel();
        BackgroundOnly15 = new javax.swing.JLabel();
        BackgroundOnly16 = new javax.swing.JLabel();
        BackgroundOnly17 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(234, 232, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Main Profile");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 150, 30));

        curvedPanel1.setBackground(new java.awt.Color(222, 212, 208));

        curvedPanel2.setBackground(new java.awt.Color(243, 242, 237));

        StudentName.setFont(new java.awt.Font("Bebas Neue", 1, 45)); // NOI18N
        StudentName.setForeground(new java.awt.Color(0, 0, 0));
        StudentName.setText("[FULL STUDENT NAME]");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 25));

        StudentNumber.setBackground(new java.awt.Color(204, 204, 204));
        StudentNumber.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        StudentNumber.setForeground(new java.awt.Color(204, 204, 204));
        StudentNumber.setText("[ # STUDENT NUMBER ]");

        RatingText.setFont(new java.awt.Font("Modern No. 20", 2, 20)); // NOI18N
        RatingText.setForeground(new java.awt.Color(130, 130, 43));
        RatingText.setText("[ CUSTOM RATING ]");

        GradeLevelText2.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        GradeLevelText2.setForeground(new java.awt.Color(0, 0, 0));
        GradeLevelText2.setText("•  Senior High School - [GRADE LEVEL]");

        GradeAndSectionText.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        GradeAndSectionText.setForeground(new java.awt.Color(0, 0, 0));
        GradeAndSectionText.setText("•  [ STRAND - GRADE LEVEL - SECTION ]");

        RegularStudentText.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        RegularStudentText.setForeground(new java.awt.Color(0, 0, 0));
        RegularStudentText.setText("•  [ REGULAR OR IRREGULAR STUDENT ]");

        StrandText1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        StrandText1.setForeground(new java.awt.Color(0, 0, 0));
        StrandText1.setText("•  [ STRAND ]");

        javax.swing.GroupLayout curvedPanel2Layout = new javax.swing.GroupLayout(curvedPanel2);
        curvedPanel2.setLayout(curvedPanel2Layout);
        curvedPanel2Layout.setHorizontalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(curvedPanel2Layout.createSequentialGroup()
                        .addComponent(StudentName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StudentNumber)
                        .addGap(90, 90, 90))
                    .addGroup(curvedPanel2Layout.createSequentialGroup()
                        .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(curvedPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RatingText)
                                    .addComponent(GradeAndSectionText)
                                    .addComponent(GradeLevelText2)
                                    .addComponent(RegularStudentText)
                                    .addComponent(StrandText1))))
                        .addGap(0, 210, Short.MAX_VALUE))))
        );
        curvedPanel2Layout.setVerticalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentName)
                    .addComponent(StudentNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RatingText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GradeLevelText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StrandText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegularStudentText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GradeAndSectionText)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout curvedPanel1Layout = new javax.swing.GroupLayout(curvedPanel1);
        curvedPanel1.setLayout(curvedPanel1Layout);
        curvedPanel1Layout.setHorizontalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel1Layout.createSequentialGroup()
                .addComponent(curvedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        curvedPanel1Layout.setVerticalGroup(
            curvedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel1Layout.createSequentialGroup()
                .addComponent(curvedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(curvedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, 1050, 310));

        curvedPanel3.setBackground(new java.awt.Color(221, 212, 208));

        curvedPanel4.setBackground(new java.awt.Color(243, 242, 237));
        curvedPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        curvedPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 937, -1));

        MobileNumberTextHolder.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        MobileNumberTextHolder.setForeground(new java.awt.Color(0, 0, 0));
        MobileNumberTextHolder.setText("• Mobile Number :");
        curvedPanel4.add(MobileNumberTextHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        GuardianMobileNumberActual.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianMobileNumberActual.setForeground(new java.awt.Color(0, 0, 0));
        GuardianMobileNumberActual.setText("[ GUARDIAN MOBILE NUMBER ]");
        curvedPanel4.add(GuardianMobileNumberActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        EmailTextHolder.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        EmailTextHolder.setForeground(new java.awt.Color(0, 0, 0));
        EmailTextHolder.setText("• E-mail :");
        curvedPanel4.add(EmailTextHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 15, -1, -1));

        GuardianEmailActual.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianEmailActual.setForeground(new java.awt.Color(0, 0, 0));
        GuardianEmailActual.setText("[ GUARDIAN EMAIL ACCOUNT ]");
        curvedPanel4.add(GuardianEmailActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 84, -1, -1));

        GuardianFacebookAccountTextHolder.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianFacebookAccountTextHolder.setForeground(new java.awt.Color(0, 0, 0));
        GuardianFacebookAccountTextHolder.setText("• Guardian Facebook Account :");
        curvedPanel4.add(GuardianFacebookAccountTextHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));

        GuardianFbAccountActual.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianFbAccountActual.setForeground(new java.awt.Color(0, 0, 0));
        GuardianFbAccountActual.setText("[ GUARDIAN FB ACCOUNT ]");
        curvedPanel4.add(GuardianFbAccountActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        curvedPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 937, -1));

        GuardianMobileNumberTextHolder.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianMobileNumberTextHolder.setForeground(new java.awt.Color(0, 0, 0));
        GuardianMobileNumberTextHolder.setText("• Guardian Mobile Number :");
        curvedPanel4.add(GuardianMobileNumberTextHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));

        FacebookAccountTextHolder1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        FacebookAccountTextHolder1.setForeground(new java.awt.Color(0, 0, 0));
        FacebookAccountTextHolder1.setText("• Facebook Account :");
        curvedPanel4.add(FacebookAccountTextHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));

        StudentMobileNumberActual1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        StudentMobileNumberActual1.setForeground(new java.awt.Color(0, 0, 0));
        StudentMobileNumberActual1.setText("[ STUDENT MOBILE NUMBER ]");
        curvedPanel4.add(StudentMobileNumberActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 15, -1, -1));

        StudentFbAccountActual1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        StudentFbAccountActual1.setForeground(new java.awt.Color(0, 0, 0));
        StudentFbAccountActual1.setText("[ STUDENT FB ACCOUNT ]");
        curvedPanel4.add(StudentFbAccountActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 45, -1, -1));

        EmailTextHolder1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        EmailTextHolder1.setForeground(new java.awt.Color(0, 0, 0));
        EmailTextHolder1.setText("• E-mail :");
        curvedPanel4.add(EmailTextHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 84, -1, -1));

        EmailActual1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        EmailActual1.setForeground(new java.awt.Color(0, 0, 0));
        EmailActual1.setText("[ STUDENT EMAIL ACCOUNT ]");
        curvedPanel4.add(EmailActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 15, -1, -1));

        GuardianNameTextHolder.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianNameTextHolder.setForeground(new java.awt.Color(0, 0, 0));
        GuardianNameTextHolder.setText("• Guardian Name : ");
        curvedPanel4.add(GuardianNameTextHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        GuardianNameActual.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        GuardianNameActual.setForeground(new java.awt.Color(0, 0, 0));
        GuardianNameActual.setText("[ GUARDIAN NAME ]");
        curvedPanel4.add(GuardianNameActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 84, -1, -1));

        javax.swing.GroupLayout curvedPanel3Layout = new javax.swing.GroupLayout(curvedPanel3);
        curvedPanel3.setLayout(curvedPanel3Layout);
        curvedPanel3Layout.setHorizontalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel3Layout.createSequentialGroup()
                .addComponent(curvedPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        curvedPanel3Layout.setVerticalGroup(
            curvedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel3Layout.createSequentialGroup()
                .addComponent(curvedPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(curvedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1230, 180));

        curvedPanel5.setBackground(new java.awt.Color(221, 212, 208));

        curvedPanel6.setBackground(new java.awt.Color(243, 242, 237));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Past Sections");

        StudentFormerSectionsActual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        StudentFormerSectionsActual.setForeground(new java.awt.Color(0, 0, 0));
        StudentFormerSectionsActual.setText("•  [ STUDENT FORMER SECTIONS ]    [ SCHOOL YEAR ]");

        javax.swing.GroupLayout curvedPanel6Layout = new javax.swing.GroupLayout(curvedPanel6);
        curvedPanel6.setLayout(curvedPanel6Layout);
        curvedPanel6Layout.setHorizontalGroup(
            curvedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curvedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(curvedPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(StudentFormerSectionsActual)
                        .addContainerGap(861, Short.MAX_VALUE))
                    .addGroup(curvedPanel6Layout.createSequentialGroup()
                        .addGroup(curvedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(curvedPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator4))
                        .addContainerGap())))
        );
        curvedPanel6Layout.setVerticalGroup(
            curvedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentFormerSectionsActual)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout curvedPanel5Layout = new javax.swing.GroupLayout(curvedPanel5);
        curvedPanel5.setLayout(curvedPanel5Layout);
        curvedPanel5Layout.setHorizontalGroup(
            curvedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel5Layout.createSequentialGroup()
                .addComponent(curvedPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        curvedPanel5Layout.setVerticalGroup(
            curvedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel5Layout.createSequentialGroup()
                .addComponent(curvedPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(curvedPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 1230, 110));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contact Information");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        BackgroundOnly6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly6.setText("jLabel1");
        jPanel2.add(BackgroundOnly6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 280, 270));

        BackgroundOnly5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly5.setText("jLabel1");
        jPanel2.add(BackgroundOnly5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 500, 260));

        BackgroundOnly2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly2.setText("jLabel1");
        jPanel2.add(BackgroundOnly2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -10, 500, 270));

        BackgroundOnly3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly3.setText("jLabel1");
        jPanel2.add(BackgroundOnly3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, -20, 280, 290));

        BackgroundOnly1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly1.setText("jLabel1");
        jPanel2.add(BackgroundOnly1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 270));

        BackgroundOnly9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly9.setText("jLabel1");
        jPanel2.add(BackgroundOnly9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 680, 340, 180));

        BackgroundOnly4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly4.setText("jLabel1");
        jPanel2.add(BackgroundOnly4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 500, 260));

        BackgroundOnly7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly7.setText("jLabel1");
        jPanel2.add(BackgroundOnly7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 540, 470, 150));

        BackgroundOnly8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly8.setText("jLabel1");
        jPanel2.add(BackgroundOnly8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 470, 180));

        BackgroundOnly10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly10.setText("jLabel1");
        jPanel2.add(BackgroundOnly10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 470, 180));

        BackgroundOnly11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly11.setText("jLabel1");
        jPanel2.add(BackgroundOnly11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 470, 180));

        BackgroundOnly12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly12.setText("jLabel1");
        jPanel2.add(BackgroundOnly12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 680, 470, 180));

        BackgroundOnly13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly13.setText("jLabel1");
        jPanel2.add(BackgroundOnly13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 470, 180));

        BackgroundOnly14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly14.setText("jLabel1");
        jPanel2.add(BackgroundOnly14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 180, 470, 180));

        BackgroundOnly15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly15.setText("jLabel1");
        jPanel2.add(BackgroundOnly15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 360, 470, 180));

        BackgroundOnly16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly16.setText("jLabel1");
        jPanel2.add(BackgroundOnly16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 340, 180));

        BackgroundOnly17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18% background 500 x 250.png"))); // NOI18N
        BackgroundOnly17.setText("jLabel1");
        jPanel2.add(BackgroundOnly17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 470, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1642, 870);
    }// </editor-fold>//GEN-END:initComponents
    public void LoadData(){
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String path = "C:\\Users\\avery\\OneDrive\\Documents\\NetBeansProjects\\Portal\\DatabaseNiBFF.accdb";
            String url = "jdbc:ucanaccess://" + path;  
            Connection connect = DriverManager.getConnection(url);
            Statement st = connect.createStatement();
            String StudentID = null;
            String query = "SELECT recentID FROM recentlogininfo WHERE ID= 1";
            ResultSet rs = st.executeQuery(query);
  
            while(rs.next()){
                StudentID = rs.getString(1);               
            }
            String query2 = "SELECT * FROM Main_Profile_ICT_12B WHERE Student_Number='"+StudentID+"'";
            ResultSet rs2 = st.executeQuery(query2);
            System.out.println(rs2);
            while(rs2.next()){
                
                String Fname = String.valueOf(rs2.getString("Student_First_Name"));
                String Lname = String.valueOf(rs2.getString("Student_Last_Name"));
                String GLevel = String.valueOf(rs2.getString("Grade_Level"));
                String Strand = String.valueOf(rs2.getString("Strand"));
                StudentName.setText(Fname +" "+ Lname);
                GradeLevelText2.setText("•  Senior High School - "+ GLevel);
                String Section = String.valueOf(rs2.getString("Student_Section"));
                GradeAndSectionText.setText("GRADE/SECTION: "+Section+"");
                StrandText1.setText(Strand);
                String mNumber = String.valueOf(rs2.getString("Mobile_Number"));
                StudentMobileNumberActual1.setText(mNumber);
                String Status = String.valueOf(rs2.getString("Status"));
                RegularStudentText.setText(Status);
                String Facebook_name = String.valueOf(rs2.getString("Facebook_name"));
                StudentFbAccountActual1.setText(Facebook_name);
                StudentNumber.setText(StudentID);
                String EMAIL = String.valueOf(rs2.getString("EMAIL"));
                EmailActual1.setText(EMAIL);
                String GuardianName = String.valueOf(rs2.getString("GuardianName"));
                GuardianNameActual.setText(GuardianName);
                String GuardianEmail = String.valueOf(rs2.getString("GuardianEmail"));
                GuardianEmailActual.setText(GuardianEmail);
                String Guardian_mobile_number = String.valueOf(rs2.getString("Guardian_mobile_number"));
                GuardianMobileNumberActual.setText(Guardian_mobile_number);
                String Guardian_facebook_account = String.valueOf(rs2.getString("Guardian_facebook_account"));
                GuardianFbAccountActual.setText(Guardian_facebook_account);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundOnly1;
    private javax.swing.JLabel BackgroundOnly10;
    private javax.swing.JLabel BackgroundOnly11;
    private javax.swing.JLabel BackgroundOnly12;
    private javax.swing.JLabel BackgroundOnly13;
    private javax.swing.JLabel BackgroundOnly14;
    private javax.swing.JLabel BackgroundOnly15;
    private javax.swing.JLabel BackgroundOnly16;
    private javax.swing.JLabel BackgroundOnly17;
    private javax.swing.JLabel BackgroundOnly2;
    private javax.swing.JLabel BackgroundOnly3;
    private javax.swing.JLabel BackgroundOnly4;
    private javax.swing.JLabel BackgroundOnly5;
    private javax.swing.JLabel BackgroundOnly6;
    private javax.swing.JLabel BackgroundOnly7;
    private javax.swing.JLabel BackgroundOnly8;
    private javax.swing.JLabel BackgroundOnly9;
    private javax.swing.JLabel EmailActual1;
    private javax.swing.JLabel EmailTextHolder;
    private javax.swing.JLabel EmailTextHolder1;
    private javax.swing.JLabel FacebookAccountTextHolder1;
    private javax.swing.JLabel GradeAndSectionText;
    private javax.swing.JLabel GradeLevelText2;
    private javax.swing.JLabel GuardianEmailActual;
    private javax.swing.JLabel GuardianFacebookAccountTextHolder;
    private javax.swing.JLabel GuardianFbAccountActual;
    private javax.swing.JLabel GuardianMobileNumberActual;
    private javax.swing.JLabel GuardianMobileNumberTextHolder;
    private javax.swing.JLabel GuardianNameActual;
    private javax.swing.JLabel GuardianNameTextHolder;
    private javax.swing.JLabel MobileNumberTextHolder;
    private javax.swing.JLabel RatingText;
    private javax.swing.JLabel RegularStudentText;
    private javax.swing.JLabel StrandText1;
    private javax.swing.JLabel StudentFbAccountActual1;
    private javax.swing.JLabel StudentFormerSectionsActual;
    private javax.swing.JLabel StudentMobileNumberActual1;
    private javax.swing.JLabel StudentName;
    private javax.swing.JLabel StudentNumber;
    private LoginAndSignup.CurvedPanel curvedPanel1;
    private LoginAndSignup.CurvedPanel curvedPanel2;
    private LoginAndSignup.CurvedPanel curvedPanel3;
    private LoginAndSignup.CurvedPanel curvedPanel4;
    private LoginAndSignup.CurvedPanel curvedPanel5;
    private LoginAndSignup.CurvedPanel curvedPanel6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
